import kaos from "../assets/kaos.png";
import sepatu from "../assets/sepatu.png";
import example1 from "../assets/example1.png";
import simanis from "../assets/simanis.jpg";
import template from "../assets/template-kosong.png";
import logo from "../assets/logo.jpg";

export const position = [
  { price: { x: 68.935, y: 28.6 }, logo: { x: 78.435, y: 0.71 } },
  { price: { x: 68.935, y: 61.94 }, logo: { x: 78.435, y: 34.1 } },
  { price: { x: 68.935, y: 85.74 }, logo: { x: 78.435, y: 66.8 } },
];

export const getPost = {
  id: "2",
  displayImg: [
    {
      id: "imgPost1",
      link: example1,
      x: 0,
      y: 0,
      width: 100,
      height: 100,
      draggable: true,
    },
    {
      id: "imgPost2",
      link: simanis,
      x: 0,
      y: 0,
      width: 100,
      height: 100,
      draggable: true,
    },
  ],
  template: {
    id: "template",
    link: template,
    x: 60,
    y: 0,
    width: 40,
    height: 100,
    transform: false,
  },
  halaman: 2,
  author: "",
  captions: "lorem10",
  products: [
    {
      id: "p1",
      halaman: 1,
      urutan: 1,
      productName: "Kaos",
      linkNo: 12,
      linkAffiliate: "",
      price: {
        id: "price1",
        text: "Rp100.000",
        x: 68.935,
        y: 28.6,
        width: 25,
        height: 3,
        align: "center",
        fontSize: 3,
        draggable: true,
      },
      img: {
        id: "img1",
        link: kaos,
        x: 71.435,
        y: 7.2,
        width: 20,
        height: 20,
        draggable: true,
      },
      logo: {
        username: "nike",
        id: "logo1",
        link: logo,
        x: 78.435,
        y: 0.71,
        width: 6,
        height: 6,
        draggable: true,
      },
    },
    {
      id: "p2",
      halaman: 1,
      urutan: 2,
      productName: "Celana",
      linkNo: 12,
      linkAffiliate: "",
      price: {
        id: "price2",
        text: "Rp31.000.000",
        x: 68.935,
        y: 61.94,
        fontSize: 3,
        width: 25,
        height: 3,
        draggable: true,
      },
      img: {
        id: "img2",
        link: kaos,
        x: 71.435,
        y: 40.5,
        width: 20,
        height: 20,
        draggable: true,
      },
      logo: {
        username: "nike",
        id: "logo2",
        link: logo,
        x: 78.435,
        y: 34.1,
        width: 6,
        height: 6,
        draggable: true,
      },
    },
    {
      id: "p3",
      halaman: 1,
      urutan: 3,
      productName: "Sepatu Nike AF1",
      linkNo: 12,
      linkAffiliate: "",
      price: {
        id: "price3",
        text: "Rp6.000.000",
        x: 68.935,
        y: 85.74,
        fontSize: 3,
        width: 25,
        height: 3,
        draggable: true,
      },
      img: {
        id: "img3",
        link: sepatu,
        x: 71.435,
        y: 73.8,
        width: 20,
        height: 20,
        draggable: true,
      },
      logo: {
        username: "karungjantan",

        id: "logo3",
        link: logo,
        x: 78.435,
        y: 66.8,
        width: 6,
        height: 6,
        draggable: true,
      },
    },
    {
      id: "p4",
      halaman: 2,
      urutan: 1,
      productName: "Kaos",
      linkNo: 12,
      linkAffiliate: "",
      price: {
        id: "price1",
        text: "Rp100.000",
        x: 68.935,
        y: 28.6,
        width: 25,
        height: 3,
        align: "center",
        fontSize: 3,
        draggable: true,
      },
      img: {
        id: "img4",
        link: kaos,
        x: 71.435,
        y: 7.2,
        width: 20,
        height: 20,
        draggable: true,
      },
      logo: {
        username: "nike",
        id: "logo1",
        link: logo,
        x: 78.435,
        y: 0.71,
        width: 6,
        height: 6,
        draggable: true,
      },
    },
    {
      id: "p5",
      halaman: 2,
      urutan: 2,
      productName: "Celana",
      linkNo: 12,
      linkAffiliate: "",
      price: {
        id: "price2",
        text: "Rp31.000.000",
        x: 68.935,
        y: 61.94,
        fontSize: 3,
        width: 25,
        height: 3,
        draggable: true,
      },
      img: {
        id: "img5",
        link: kaos,
        x: 71.435,
        y: 40.5,
        width: 20,
        height: 20,
        draggable: true,
      },
      logo: {
        username: "nike",
        id: "logo2",
        link: logo,
        x: 78.435,
        y: 34.1,
        width: 6,
        height: 6,
        draggable: true,
      },
    },
  ],
};

export const menuData = [
  { value: 10, label: "Sepuluh" },
  { value: 20, label: "dua puluh" },
  { value: 30, label: "tiga puluh" },
];
